apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-disk-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: /SATA-EBS
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
